export enum CHAIN_NAMES {
    MAINNET = 'mainnet',
    SEPOLIA = 'sepolia',
    BASE_SEPOLIA = 'baseSepolia',
}

export const CHAIN_IDS = {
    [CHAIN_NAMES.MAINNET]: 1,
    [CHAIN_NAMES.SEPOLIA]: 11155111,
    [CHAIN_NAMES.BASE_SEPOLIA]: 84532,
}

export enum KNOWN_NETWORK {
    MAINNET = CHAIN_NAMES.MAINNET,
    SEPOLIA = CHAIN_NAMES.SEPOLIA,
    BASE_SEPOLIA = CHAIN_NAMES.BASE_SEPOLIA,
}

export const KNOWN_CHAIN_IDS = {
    [KNOWN_NETWORK.MAINNET]: 1,
    [KNOWN_NETWORK.SEPOLIA]: 11155111,
    [KNOWN_NETWORK.BASE_SEPOLIA]: 84532,
} as const
